# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: miguel.ibero.me
email: miguel@ibero.me
description: > # this means to ignore newlines until "baseurl:"
  My name is Miguel Ibero and I am a software developer from Barcelona, Spain.
  This is my personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://miguel.ibero.me" # the base hostname & protocol for your site
twitter_username: miguel_ibero
github_username:  miguelibero
disqus_shortname: miguel-ibero-me

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: pygments
